name: deoldify-mm
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch=1.11.0
  - torchvision=0.12.0
  - ffmpeg
  - openh264
  - pip:
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorama==0.4.6
      - crcmod==1.7
      - cryptography==43.0.3
      - filelock==3.14.0
      - idna==3.10
      - jmespath==0.10.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - model-index==0.1.11
      - numpy<2
      - opendatalab==0.0.10
      - openmim
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.1
      - pandas==2.2.3
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.2
      - requests==2.28.2
      - rich==13.4.2
      - setuptools==60.2.0
      - six==1.16.0
      - tabulate==0.9.0
      - tqdm==4.65.2
      - tzdata==2024.2
      - urllib3==1.26.20
